# Generated by Django 5.2.6 on 2025-09-11 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='role',
            field=models.CharField(choices=[('donour', 'Donor'), ('reliefcamp', 'ReliefCamp')], max_length=20),
        ),
    ]
