# Generated by Django 5.2.6 on 2025-09-19 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_reliefcamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='reliefcamp',
            name='name',
            field=models.CharField(default='Unnamed Relief Camp', max_length=150),
        ),
    ]
