# Generated by Django 5.2.6 on 2025-09-19 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_reliefcamp_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='name',
            field=models.CharField(default='user', max_length=150),
        ),
    ]
