# Generated by Django 5.2.4 on 2025-09-19 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_donationcategory_donationitem_donationrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('icon', models.CharField(blank=True, choices=[('fa-solid fa-bottle-baby', 'Baby Food'), ('fa-solid fa-shirt', 'Clothing & Apparel'), ('fa-solid fa-kit-medical', 'Medical Supplies'), ('fa-solid fa-soap', 'Hygiene & Sanitary Items'), ('fa-solid fa-tint', 'Water & Beverages'), ('fa-solid fa-can-food', 'Canned & Dry Foods'), ('fa-solid fa-bed', 'Shelter & Bedding'), ('fa-solid fa-book', 'Educational Supplies'), ('fa-solid fa-broom', 'Cleaning Supplies')], help_text="Font Awesome classes, e.g. 'fa-solid fa-bottle-baby'", max_length=120, null=True)),
            ],
        ),
    ]
