# Generated by Django 5.2.6 on 2025-09-20 10:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReliefCampRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('quantity', models.PositiveIntegerField()),
                ('unit', models.CharField(default='units', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('fulfilled', 'Fulfilled')], default='pending', max_length=20)),
                ('camp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='home.reliefcamp')),
            ],
        ),
    ]
