# Generated by Django 5.2.6 on 2025-09-20 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_reliefcamprequest'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reliefcamprequest',
            old_name='description',
            new_name='notes',
        ),
        migrations.RemoveField(
            model_name='reliefcamprequest',
            name='title',
        ),
        migrations.AddField(
            model_name='reliefcamprequest',
            name='category',
            field=models.CharField(default='General', max_length=100),
        ),
        migrations.AddField(
            model_name='reliefcamprequest',
            name='contact_person',
            field=models.CharField(default='General', max_length=100),
        ),
        migrations.AddField(
            model_name='reliefcamprequest',
            name='date_needed',
            field=models.DateField(default='2000-01-01'),
        ),
        migrations.AddField(
            model_name='reliefcamprequest',
            name='justification',
            field=models.TextField(default='Not provided'),
        ),
        migrations.AddField(
            model_name='reliefcamprequest',
            name='location',
            field=models.CharField(default='Unknown', max_length=255),
        ),
        migrations.AddField(
            model_name='reliefcamprequest',
            name='people',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reliefcamprequest',
            name='phone',
            field=models.CharField(default='0000000000', max_length=20),
        ),
        migrations.AddField(
            model_name='reliefcamprequest',
            name='urgency',
            field=models.CharField(choices=[('Normal', 'Normal'), ('High', 'High'), ('Urgent', 'Urgent')], default='Normal', max_length=20),
        ),
    ]
