# Generated by Django 5.2.6 on 2025-09-20 17:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_rename_description_reliefcamprequest_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reliefcamprequest',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='camp_requests', to='home.donationitem'),
        ),
        migrations.AlterField(
            model_name='reliefcamprequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('allocated', 'Allocated'), ('approved', 'Approved'), ('fulfilled', 'Fulfilled')], default='pending', max_length=20),
        ),
    ]
