# Generated by Django 5.2.6 on 2025-09-20 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_reliefcamprequest_item_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reliefcamprequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('allocated', 'Allocated')], default='pending', max_length=20),
        ),
    ]
