# Generated by Django 5.2.6 on 2025-09-21 09:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_alter_reliefcamprequest_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='reliefcamprequest',
            name='allocated_donation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='allocated_requests', to='home.donationrequest'),
        ),
    ]
