# Generated by Django 5.2.6 on 2025-09-24 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_reliefcamprequest_allocated_donation'),
    ]

    operations = [
        migrations.AddField(
            model_name='reliefcamprequest',
            name='razorpay_order_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
