# Generated by Django 5.2.6 on 2025-09-25 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_reliefcamprequest_razorpay_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='donationitem',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
